# Generated by Django 5.1 on 2024-08-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=1)),
                ('grade', models.IntegerField()),
                ('color', models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('LG', 'Light green'), ('DG', 'Dark green'), ('Bu', 'Blue'), ('Pu', 'Purple'), ('Bk', 'Black'), ('Pi', 'Pink'), ('W', 'White')], default='R', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('setter', models.CharField(choices=[('K', 'KB'), ('A', 'APE'), ('O', 'OK'), ('T', 'TOPS'), ('F', 'firewx'), ('M', 'Merm'), ('S', 'Sunny'), ('C', 'Chalk Snorter'), ('MD', 'McDeee')], default='K', max_length=2)),
                ('date_set', models.DateField()),
                ('date_logged', models.DateTimeField()),
                ('archived', models.BooleanField()),
                ('archived_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugested_grade', models.IntegerField()),
                ('feedback', models.CharField(max_length=350)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routesetting.route')),
            ],
        ),
    ]
