# Generated by Django 5.1 on 2024-08-25 03:20

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['grade_num']},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='grade',
            new_name='grade_num',
        ),
        migrations.RemoveField(
            model_name='routefeedback',
            name='sugested_grade',
        ),
        migrations.AddField(
            model_name='routefeedback',
            name='date',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routefeedback',
            name='grade_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routefeedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routefeedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='routefeedback',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routesetting.route'),
        ),
    ]
