# Generated by Django 5.0.7 on 2024-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0002_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.PositiveIntegerField(max_length=1),
        ),
    ]
