# Generated by Django 5.1 on 2024-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0003_alter_route_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='setter',
            field=models.CharField(choices=[('K', 'KB'), ('A', 'APE'), ('O', 'OK'), ('T', 'TOPS'), ('F', 'firewx'), ('M', 'Merm'), ('S', 'Sunny'), ('C', 'Chalk Snorter'), ('MD', 'McDeee'), ('TB', 'TBear'), ('ST', 'Steel toes'), ('B', 'Blackbear')], default='K', max_length=2),
        ),
    ]
