# Generated by Django 5.0.7 on 2024-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0003_alter_route_grade_alter_route_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
