# Generated by Django 5.1 on 2024-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0004_alter_route_grade_alter_route_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.CharField(default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(max_length=3),
        ),
    ]
