# Generated by Django 5.1 on 2024-08-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0005_route_type_alter_route_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.IntegerField(choices=[(0, 'V0'), (10, 'V1'), (20, 'V2')]),
        ),
    ]
