# Generated by Django 5.1 on 2024-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0006_alter_route_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
