# Generated by Django 5.1 on 2024-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routesetting', '0008_alter_route_setter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='setter',
            field=models.CharField(choices=[('K', 'KB'), ('A', 'APE'), ('O', 'OK'), ('T', 'TOPS'), ('F', 'firewx'), ('M', 'Merm'), ('S', 'Sunny'), ('C', 'Chalk Snorter'), ('MD', 'McDeee')], default='K', max_length=2),
        ),
    ]
