# Generated by Django 5.1 on 2024-08-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_testing', '0002_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='grade',
        ),
        migrations.AddField(
            model_name='route',
            name='grade_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='grade_type',
            field=models.CharField(default='T', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
