# Generated by Django 5.1 on 2024-08-24 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_testing', '0003_remove_route_grade_route_grade_num_route_grade_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=300)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_testing.route')),
            ],
        ),
    ]
