# Generated by Django 5.1 on 2024-08-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_testing', '0005_alter_route_options_alter_routefeedback_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routefeedback',
            old_name='grade',
            new_name='grade_int',
        ),
    ]
