# Generated by Django 5.1 on 2024-08-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_testing', '0006_rename_grade_routefeedback_grade_int'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='grade_type',
            new_name='type',
        ),
    ]
